/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-04-08T09:21:07.258363+09:00[Asia/Tokyo]")

@Validated
@Api(value = "streams", description = "the streams API")
public interface StreamsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "", nickname = "streamsPost", notes = "subscribes a client to receive out-of-band data", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "subscription successfully created", response = Object.class) })
    @RequestMapping(value = "/streams",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Object> streamsPost(@NotNull @ApiParam(value = "the location where data will be sent.  Must be network accessible by the source server ", required = true) @Valid @RequestParam(value = "callbackUrl", required = true) String callbackUrl) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
